Repository pystage/pystage, pull requests merged in 2024-06, with the labels that each got.

#63 Implemented think/say for sec block
  src/pystage/core/_looks.py
  src/pystage/core/code_block.py
  src/pystage/core/gui.py
Labels: questions and minor changes

#60 Fix say for secs
  src/pystage/core/gui.py
Labels: missing block

#115 Added support for cloning
  src/example_clones.py
  src/pystage/convert/sb3_templates.py
  src/pystage/core/_base_sprite.py
  src/pystage/core/_control.py
  src/pystage/core/_looks.py
  src/pystage/core/code_block.py
  src/pystage/core/sprite.py
  src/pystage/core/stage.py
  src/pystage/en/sprite.py
Labels: missing block

#59 Implemented all the sub blocks in "set __ effect to __" block from Scratch.
  src/pystage/convert/code_writer.py
  src/pystage/convert/sb3_templates.py
  src/pystage/core/_looks.py
  src/pystage/core/assets.py
  src/pystage/core/stage.py
Labels: help wanted, missing block
